version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: user-tasks-nginx
    ports:
      - "8081:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - testing-network

  php-fpm:
    build: ./docker/php
    container_name: user-tasks-php
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
      - PHP_FPM_TIMEOUT=${HTTPD_TIMEOUT_TO_PHP_FPM:-180}
    volumes:
      - ./:/var/www/html
    networks:
      - testing-network

networks:
  testing-network:
    name: testing-network
    driver: bridge

volumes:
  my-data:
